DROP TABLE IF EXISTS bank cascade ;

DROP TABLE IF EXISTS customer cascade ;

DROP TABLE IF EXISTS company cascade;

DROP TABLE IF EXISTS card cascade ;

DROP TABLE IF EXISTS transactions;

CREATE TABLE bank(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL,
    address VARCHAR(250) NOT NULL
);

CREATE TABLE customer(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)   NOT NULL,
    lastname  VARCHAR(25)   NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15),
    email     VARCHAR(25) UNIQUE NOT NULL
);
CREATE TABLE company
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE card (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer (id),
    card_number VARCHAR(255) NOT NULL,
    card_type VARCHAR(191) NOT NULL,
    expired_date DATE NOT NULL,
    csv VARCHAR(3) NOT NULL,
    bank_id INT NOT NULL,
    FOREIGN KEY (bank_id) REFERENCES bank (id));

CREATE TABLE transactions(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id INT NOT NULL,
    FOREIGN KEY (card_id) REFERENCES card (id),
    company_id INT NOT NULL,
    FOREIGN KEY (company_id) REFERENCES company (id),
    price VARCHAR(20) NOT NULL

);

INSERT INTO bank(name, address) VALUES ('Bank 1', 'Aksaray/İstanbul'),
                                       ('Bank 2', 'Üsküdar/İstanbul');

INSERT INTO customer(firstname, lastname, gender, age, phone, email)
VALUES ('Emre', 'Kaya', 'male', 27, '905554443322', 'emrekaya@mail.com'),
       ('Aslı', 'Emel', 'female', 26, '905554443322', 'asliemel@mail.com'),
       ('Aytug', 'Kara', 'male', 27, '905554443322', 'aytugkara@mail.com'),
       ('Hikmet', 'Özay', 'male', 25, '905554443322', 'hikmetozay@mail.com');

INSERT INTO company(name)
VALUES ('Netflix'),
       ('Burger King'),
       ('Youtube'),
       ('Migros');



INSERT INTO card( customer_id, card_number, card_type, expired_date, csv, bank_id)
VALUES  (1, '4111 1111 1111 1111', 'visa', '2029-01-01', '222', 1),
        (2, '5500 0000 0000 0004', 'masterCard', '2027-01-01', '111', 2);

INSERT INTO transactions(card_id, company_id, price) VALUES (1, 2, '35')