DROP TABLE IF EXISTS bank;

DROP TABLE IF EXISTS customer;


CREATE TABLE bank(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL,
    address VARCHAR(250) NOT NULL
);

CREATE TABLE customer(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15),
    email     VARCHAR(25) UNIQUE NOT NULL
);

INSERT INTO bank(name, address) VALUES ('Garanti Bankası', 'Sefaköy/İstanbul'),
                                       ('Akbank', 'Sefaköy/İstanbul');

INSERT INTO customer(firstname, lastname, gender, age, phone, email)
VALUES ('Emre', 'Kaya', 'male', 27, '905554443322', 'emrekaya@gmail.com'),
       ('Ceren', 'Telli', 'female', 26, '905554443322', 'ali2@gmail.com'),
       ('Dilek', 'Tutku', 'female', 14, '905554443322', 'ali3@gmail.com'),
       ('Cem', 'Saygın', 'male', 25, '905554443322', 'ali4@gmail.com'),
       ('Semih', 'Sanlı', 'male', 25, '905554443322', 'ali5@gmail.com'),
       ('Veli', 'Telli', 'female', 26, '905554443322', 'veli@hotmail.com'),
       ('Kamil', 'Tutku', 'female', 14, '905554443322', 'veli2@hotmail.com'),
       ('Sam', 'Caroline', 'male', 25, '905554443322', 'veli3@hotmail.com'),
       ('Jhonny', 'Deepy', 'male', 41, '905554443322', 'jhonny@gmail.com'),
       ('Fatih', 'Telli', 'female', 34, '905554443322', 'veli5@hotmail.com'),
       ('Semra', 'Kelebek', 'female', 44, '905554443322', 'veli6@hotmail.com'),
       ('Mustafa', 'Saygın', 'male', 12, '905554443322', 'musti@daddy.com'),
       ('Carl', 'Geenny', 'male', 27, '905554443322', 'veli10@hotmail.com');